In [4]:
import pandas as pd
import numpy as np
import os
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.diagnostic import het_breuschpagan
from scipy.stats import shapiro
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
path_data_clean = "../data_clean/"

file_data_bersih = os.path.join(path_data_clean, "dataset_final_2021-2024.csv")


df = pd.read_csv(file_data_bersih)
df.head()

,Wilayah,Tahun,P1,UHH,HLS,RLS,Pengeluaran,TPT,Kepadatan
0,Kabupaten Cilacap,2021,1.48,73.90,12.63,7.09,10534,9.97,924
1,Kabupaten Banyumas,2021,2.35,73.80,13.03,7.63,11546,6.05,1340
2,Kabupaten Purbalingga,2021,2.10,73.21,12.00,7.25,10032,6.05,1487
3,Kabupaten Banjarnegara,2021,2.97,74.28,11.63,6.75,9407,5.86,1003
4,Kabupaten Kebumen,2021,3.24,73.55,13.35,7.55,9028,6.03,1124

In [6]:
print(df.shape)

(140, 9)

Data terdiri dari 105 baris, 8 kolom

In [7]:
print("Jumlah data duplikat: ", df.duplicated().sum())

Jumlah data duplikat:  0

In [8]:
print(df.isna().sum())

Wilayah        0
Tahun          0
P1             0
UHH            0
HLS            0
RLS            0
Pengeluaran    0
TPT            0
Kepadatan      0
dtype: int64

In [9]:
print(df.describe())

             Tahun          P1         UHH         HLS       RLS  \
count   140.000000  140.000000  140.000000  140.000000  140.0000
mean   2022.500000    1.590643   75.201714   13.031000    8.1740
std       1.122048    0.674892    1.810811    0.913436    1.2933
min    2021.000000    0.470000   69.540000   11.630000    6.2200
25%    2021.750000    1.020000   74.167500   12.450000    7.2975
50%    2022.500000    1.525000   75.000000   12.900000    7.8050
75%    2023.250000    1.980000   76.470000   13.360000    8.8575
max    2024.000000    3.410000   78.260000   15.570000   11.4800

        Pengeluaran         TPT     Kepadatan
count    140.000000  140.000000    140.000000
mean   11790.107143    5.151000   2112.557143
std     1850.027076    1.875406   2399.331982
min     8573.000000    1.760000    461.000000
25%    10512.000000    3.800000    935.750000
50%    11413.500000    4.955000   1182.000000
75%    12772.500000    6.052500   1846.000000
max    17096.000000    9.970000  11878.000000

PENGERJAAN

STEP 1 — Pisahkan data
- Train = tahun 2021 - 2023
- Test = tahun 2024

In [10]:
df_train = df[df["Tahun"].isin([2021, 2022, 2023])].copy()
df_test  = df[df["Tahun"] == 2024].copy()

print(df_train.shape, df_test.shape)

(105, 9) (35, 9)

STEP 2 — Uji signifikansi sederhana (satu-satu hubungan)

Regress:
- P1 ~ UHH
- P1 ~ HLS
- P1 ~ RLS
- P1 ~ Pengeluaran
- P1 ~ TPT
- P1 ~ Kepadatan

Tujuan uji ini: melihat variabel mana yang memiliki hubungan jelas dengan Y.

In [11]:
def simple_regression(df, x):
    X = sm.add_constant(df[[x]])
    y = df["P1"]
    model = sm.OLS(y, X).fit()
    print(f"\n===== P1 ~ {x} =====")
    print(model.summary())

for col in ["UHH", "HLS", "RLS", "Pengeluaran", "TPT", "Kepadatan"]:
    simple_regression(df_train, col)

===== P1 ~ UHH =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.355
Model:                            OLS   Adj. R-squared:                  0.348
Method:                 Least Squares   F-statistic:                     56.63
Date:                Fri, 05 Dec 2025   Prob (F-statistic):           2.06e-11
Time:                        11:25:13   Log-Likelihood:                -86.734
No. Observations:                 105   AIC:                             177.5
Df Residuals:                     103   BIC:                             182.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         18.7358      2.275      8.234      0.000      14.223      23.248
UHH           -0.2279      0.030     -7.525      0.000      -0.288      -0.168
==============================================================================
Omnibus:                        0.780   Durbin-Watson:                   1.857
Prob(Omnibus):                  0.677   Jarque-Bera (JB):                0.380
Skew:                           0.099   Prob(JB):                        0.827
Kurtosis:                       3.218   Cond. No.                     3.14e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.14e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

===== P1 ~ HLS =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.318
Model:                            OLS   Adj. R-squared:                  0.311
Method:                 Least Squares   F-statistic:                     47.98
Date:                Fri, 05 Dec 2025   Prob (F-statistic):           3.82e-10
Time:                        11:25:13   Log-Likelihood:                -89.660
No. Observations:                 105   AIC:                             183.3
Df Residuals:                     103   BIC:                             188.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.1776      0.805      8.921      0.000       5.582       8.773
HLS           -0.4272      0.062     -6.927      0.000      -0.550      -0.305
==============================================================================
Omnibus:                       14.050   Durbin-Watson:                   2.035
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               15.310
Skew:                           0.841   Prob(JB):                     0.000474
Kurtosis:                       3.819   Cond. No.                         189.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

===== P1 ~ RLS =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.388
Model:                            OLS   Adj. R-squared:                  0.382
Method:                 Least Squares   F-statistic:                     65.35
Date:                Fri, 05 Dec 2025   Prob (F-statistic):           1.27e-12
Time:                        11:25:13   Log-Likelihood:                -83.940
No. Observations:                 105   AIC:                             171.9
Df Residuals:                     103   BIC:                             177.2
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.3786      0.346     12.670      0.000       3.693       5.064
RLS           -0.3398      0.042     -8.084      0.000      -0.423      -0.256
==============================================================================
Omnibus:                        6.350   Durbin-Watson:                   2.059
Prob(Omnibus):                  0.042   Jarque-Bera (JB):                5.940
Skew:                           0.571   Prob(JB):                       0.0513
Kurtosis:                       3.234   Cond. No.                         54.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

===== P1 ~ Pengeluaran =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.282
Model:                            OLS   Adj. R-squared:                  0.275
Method:                 Least Squares   F-statistic:                     40.48
Date:                Fri, 05 Dec 2025   Prob (F-statistic):           5.57e-09
Time:                        11:25:13   Log-Likelihood:                -92.333
No. Observations:                 105   AIC:                             188.7
Df Residuals:                     103   BIC:                             194.0
Df Model:                           1
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           3.9595      0.372     10.630      0.000       3.221       4.698
Pengeluaran    -0.0002   3.18e-05     -6.362      0.000      -0.000      -0.000
==============================================================================
Omnibus:                        5.541   Durbin-Watson:                   2.389
Prob(Omnibus):                  0.063   Jarque-Bera (JB):                5.364
Skew:                           0.502   Prob(JB):                       0.0684
Kurtosis:                       2.532   Cond. No.                     7.59e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.59e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

===== P1 ~ TPT =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.005
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.5691
Date:                Fri, 05 Dec 2025   Prob (F-statistic):              0.452
Time:                        11:25:13   Log-Likelihood:                -109.45
No. Observations:                 105   AIC:                             222.9
Df Residuals:                     103   BIC:                             228.2
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.4769      0.199      7.425      0.000       1.082       1.871
TPT            0.0263      0.035      0.754      0.452      -0.043       0.096
==============================================================================
Omnibus:                        6.130   Durbin-Watson:                   1.766
Prob(Omnibus):                  0.047   Jarque-Bera (JB):                6.225
Skew:                           0.564   Prob(JB):                       0.0445
Kurtosis:                       2.614   Cond. No.                         17.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

===== P1 ~ Kepadatan =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.153
Model:                            OLS   Adj. R-squared:                  0.145
Method:                 Least Squares   F-statistic:                     18.67
Date:                Fri, 05 Dec 2025   Prob (F-statistic):           3.59e-05
Time:                        11:25:13   Log-Likelihood:                -100.99
No. Observations:                 105   AIC:                             206.0
Df Residuals:                     103   BIC:                             211.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.8552      0.083     22.324      0.000       1.690       2.020
Kepadatan     -0.0001    2.6e-05     -4.321      0.000      -0.000   -6.07e-05
==============================================================================
Omnibus:                        8.659   Durbin-Watson:                   2.112
Prob(Omnibus):                  0.013   Jarque-Bera (JB):                9.250
Skew:                           0.707   Prob(JB):                      0.00980
Kurtosis:                       2.658   Cond. No.                     4.26e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.26e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

STEP 3 — Bangun model regresi linier berganda (X1…X6)

Lakukan:
- uji F
- uji t
- cek VIF
- backward elimination kalau ada variabel tidak signifikan
- pilih model final

In [12]:
X_cols = ["UHH","HLS","RLS","Pengeluaran","TPT","Kepadatan"]
X_train = sm.add_constant(df_train[X_cols])
y_train = df_train["P1"]

model_full = sm.OLS(y_train, X_train).fit()
print(model_full.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.438
Model:                            OLS   Adj. R-squared:                  0.404
Method:                 Least Squares   F-statistic:                     12.74
Date:                Fri, 05 Dec 2025   Prob (F-statistic):           1.37e-10
Time:                        11:25:17   Log-Likelihood:                -79.455
No. Observations:                 105   AIC:                             172.9
Df Residuals:                      98   BIC:                             191.5
Df Model:                           6
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          13.7361      3.866      3.553      0.001       6.065      21.407
UHH            -0.1456      0.057     -2.553      0.012      -0.259      -0.032
HLS             0.0925      0.170      0.544      0.588      -0.245       0.430
RLS            -0.2160      0.174     -1.245      0.216      -0.560       0.128
Pengeluaran -3.997e-05   5.18e-05     -0.772      0.442      -0.000    6.28e-05
TPT            -0.0356      0.039     -0.921      0.359      -0.112       0.041
Kepadatan    1.072e-05   4.14e-05      0.259      0.796   -7.15e-05    9.29e-05
==============================================================================
Omnibus:                        1.132   Durbin-Watson:                   2.103
Prob(Omnibus):                  0.568   Jarque-Bera (JB):                0.806
Skew:                           0.208   Prob(JB):                        0.668
Kurtosis:                       3.104   Cond. No.                     8.87e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.87e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [13]:
# cek uji multikolinearitas (VIF)
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

vif_df = pd.DataFrame()
vif_df["feature"] = X_cols
vif_df["VIF"] = [variance_inflation_factor(df_train[X_cols].values, i)
                 for i in range(len(X_cols))]

vif_df

       feature          VIF
0          UHH   597.255441
1          HLS  1750.062966
2          RLS   534.719763
3  Pengeluaran   135.339262
4          TPT    15.226260
5    Kepadatan     5.855145

In [14]:
# Backward elimination jika ada variabel tidak signifikan
def backward_elimination(X, y, alpha=0.05):
    X = sm.add_constant(X)
    while True:
        model = sm.OLS(y, X).fit()
        pvals = model.pvalues.drop("const")
        max_p = pvals.max()
        if max_p > alpha:
            drop_var = pvals.idxmax()
            print("Drop:", drop_var, "(p =", max_p, ")")
            X = X.drop(columns=[drop_var])
        else:
            break
    return model, X.columns

model_final, selected_features = backward_elimination(df_train[X_cols], y_train)
print(selected_features)
print(model_final.summary())

Drop: Kepadatan (p = 0.796405838152286 )
Drop: HLS (p = 0.6318162657846371 )
Drop: Pengeluaran (p = 0.46089606709343534 )
Drop: TPT (p = 0.37942852554022677 )
Index(['const', 'UHH', 'RLS'], dtype='object')
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.429
Model:                            OLS   Adj. R-squared:                  0.418
Method:                 Least Squares   F-statistic:                     38.34
Date:                Fri, 05 Dec 2025   Prob (F-statistic):           3.83e-13
Time:                        11:25:34   Log-Likelihood:                -80.304
No. Observations:                 105   AIC:                             166.6
Df Residuals:                     102   BIC:                             174.6
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         11.9955      2.836      4.229      0.000       6.370      17.621
UHH           -0.1144      0.042     -2.705      0.008      -0.198      -0.030
RLS           -0.2197      0.060     -3.646      0.000      -0.339      -0.100
==============================================================================
Omnibus:                        2.975   Durbin-Watson:                   2.037
Prob(Omnibus):                  0.226   Jarque-Bera (JB):                2.343
Skew:                           0.309   Prob(JB):                        0.310
Kurtosis:                       3.393   Cond. No.                     4.17e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.17e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

STEP 4 — Prediksi tahun 2024 (test set)

- Ambil model final dari train (2021–2023)
- Prediksi P1 tahun 2024
- Hitung MAE, RMSE, MAPE

In [15]:
use_cols = [c for c in selected_features if c != "const"]

X_test = sm.add_constant(df_test[use_cols])
df_test["P1_pred"] = model_final.predict(X_test)

df_test[["Wilayah", "Tahun", "P1", "P1_pred"]]

                    Wilayah  Tahun    P1   P1_pred
105       Kabupaten Cilacap   2024  1.59  1.840160
106      Kabupaten Banyumas   2024  2.09  1.754395
107   Kabupaten Purbalingga   2024  2.10  1.964472
108  Kabupaten Banjarnegara   2024  2.38  1.946333
109       Kabupaten Kebumen   2024  2.35  1.806649
110     Kabupaten Purworejo   2024  1.08  1.457958
111      Kabupaten Wonosobo   2024  2.41  2.198236
112      Kabupaten Magelang   2024  1.23  1.759394
113      Kabupaten Boyolali   2024  1.56  1.457066
114        Kabupaten Klaten   2024  1.46  1.112582
115     Kabupaten Sukoharjo   2024  1.21  0.873154
116      Kabupaten Wonogiri   2024  1.53  1.518992
117   Kabupaten Karanganyar   2024  1.63  1.049404
118        Kabupaten Sragen   2024  2.42  1.550532
119      Kabupaten Grobogan   2024  1.90  1.787699
120         Kabupaten Blora   2024  1.59  1.840043
121       Kabupaten Rembang   2024  2.76  1.721892
122          Kabupaten Pati   2024  1.17  1.520253
123         Kabupaten Kudus   2024  1.02  1.124560
124        Kabupaten Jepara   2024  0.71  1.461398
125         Kabupaten Demak   2024  1.95  1.507240
126      Kabupaten Semarang   2024  0.91  1.493577
127    Kabupaten Temanggung   2024  0.97  1.653751
128        Kabupaten Kendal   2024  0.91  1.747145
129        Kabupaten Batang   2024  1.25  1.857866
130    Kabupaten Pekalongan   2024  1.16  1.887776
131      Kabupaten Pemalang   2024  2.56  2.091089
132         Kabupaten Tegal   2024  0.97  2.124602
133        Kabupaten Brebes   2024  2.50  2.547251
134           Kota Magelang   2024  0.92  0.616012
135          Kota Surakarta   2024  1.14  0.613247
136           Kota Salatiga   2024  0.61  0.521528
137           Kota Semarang   2024  0.59  0.618308
138         Kota Pekalongan   2024  0.83  1.387540
139              Kota Tegal   2024  1.34  1.392719

In [16]:
y_true = df_test["P1"]
y_pred = df_test["P1_pred"]

mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

print("MAE:", mae)
print("RMSE:", rmse)
print("MAPE:", mape)

MAE: 0.4223936854499217
RMSE: 0.5122841275654858
MAPE: 33.478875283264856