In [2]:
import pandas as pd
import numpy as np
import os
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.diagnostic import het_breuschpagan
from scipy.stats import shapiro
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
path_data_clean = "../data_clean/"

file_data_bersih = os.path.join(path_data_clean, "dataset_final_2021-2023.csv")


df = pd.read_csv(file_data_bersih)
df.head()

,Wilayah,Tahun,P1,UHH,HLS,RLS,Pengeluaran,TPT,Kepadatan
0,Kabupaten Cilacap,2021,1.48,73.90,12.63,7.09,10534,9.97,924
1,Kabupaten Banyumas,2021,2.35,73.80,13.03,7.63,11546,6.05,1340
2,Kabupaten Purbalingga,2021,2.10,73.21,12.00,7.25,10032,6.05,1487
3,Kabupaten Banjarnegara,2021,2.97,74.28,11.63,6.75,9407,5.86,1003
4,Kabupaten Kebumen,2021,3.24,73.55,13.35,7.55,9028,6.03,1124

In [5]:
print(df.shape)

(105, 9)

Data terdiri dari 105 baris, 8 kolom

In [6]:
print("Jumlah data duplikat: ", df.duplicated().sum())

Jumlah data duplikat:  0

In [7]:
print(df.isna().sum())

Wilayah        0
Tahun          0
P1             0
UHH            0
HLS            0
RLS            0
Pengeluaran    0
TPT            0
Kepadatan      0
dtype: int64

In [8]:
print(df.describe())

             Tahun          P1         UHH         HLS         RLS  \
count   105.000000  105.000000  105.000000  105.000000  105.000000
mean   2022.000000    1.618000   75.119333   13.012667    8.125048
std       0.820413    0.691389    1.807124    0.912235    1.267850
min    2021.000000    0.470000   69.540000   11.630000    6.220000
25%    2021.000000    1.030000   74.030000   12.440000    7.260000
50%    2022.000000    1.570000   74.870000   12.890000    7.790000
75%    2023.000000    1.950000   76.390000   13.350000    8.790000
max    2023.000000    3.410000   77.930000   15.550000   11.240000

        Pengeluaran         TPT     Kepadatan
count    105.000000  105.000000    105.000000
mean   11565.742857    5.361429   2113.942857
std     1814.000631    1.947240   2413.246293
min     8573.000000    1.760000    461.000000
25%    10277.000000    4.050000    930.000000
50%    11110.000000    5.030000   1180.000000
75%    12522.000000    6.350000   1846.000000
max    16650.000000    9.970000  11878.000000

PENGERJAAN

STEP 1 — Pisahkan data
- Train = tahun 2021 & 2022
- Test = tahun 2023

In [9]:
df_train = df[df["Tahun"].isin([2021, 2022])].copy()
df_test  = df[df["Tahun"] == 2023].copy()

print(df_train.shape, df_test.shape)

(70, 9) (35, 9)

STEP 2 — Uji signifikansi sederhana (satu-satu hubungan)

Regress:
- P1 ~ UHH
- P1 ~ HLS
- P1 ~ RLS
- P1 ~ Pengeluaran
- P1 ~ TPT
- P1 ~ Kepadatan

Tujuan uji ini: melihat variabel mana yang memiliki hubungan jelas dengan Y.

In [10]:
def simple_regression(df, x):
    X = sm.add_constant(df[[x]])
    y = df["P1"]
    model = sm.OLS(y, X).fit()
    print(f"\n===== P1 ~ {x} =====")
    print(model.summary())

for col in ["UHH", "HLS", "RLS", "Pengeluaran", "TPT", "Kepadatan"]:
    simple_regression(df_train, col)

===== P1 ~ UHH =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.344
Model:                            OLS   Adj. R-squared:                  0.334
Method:                 Least Squares   F-statistic:                     35.65
Date:                Fri, 28 Nov 2025   Prob (F-statistic):           9.56e-08
Time:                        15:56:55   Log-Likelihood:                -59.435
No. Observations:                  70   AIC:                             122.9
Df Residuals:                      68   BIC:                             127.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         18.7384      2.861      6.549      0.000      13.029      24.448
UHH           -0.2275      0.038     -5.971      0.000      -0.304      -0.151
==============================================================================
Omnibus:                        1.161   Durbin-Watson:                   1.925
Prob(Omnibus):                  0.560   Jarque-Bera (JB):                0.663
Skew:                           0.215   Prob(JB):                        0.718
Kurtosis:                       3.205   Cond. No.                     3.13e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.13e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

===== P1 ~ HLS =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.318
Model:                            OLS   Adj. R-squared:                  0.308
Method:                 Least Squares   F-statistic:                     31.71
Date:                Fri, 28 Nov 2025   Prob (F-statistic):           3.70e-07
Time:                        15:56:55   Log-Likelihood:                -60.792
No. Observations:                  70   AIC:                             125.6
Df Residuals:                      68   BIC:                             130.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.2748      1.000      7.278      0.000       5.280       9.269
HLS           -0.4321      0.077     -5.631      0.000      -0.585      -0.279
==============================================================================
Omnibus:                       12.794   Durbin-Watson:                   2.133
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               13.572
Skew:                           0.947   Prob(JB):                      0.00113
Kurtosis:                       4.031   Cond. No.                         187.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

===== P1 ~ RLS =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.379
Model:                            OLS   Adj. R-squared:                  0.370
Method:                 Least Squares   F-statistic:                     41.59
Date:                Fri, 28 Nov 2025   Prob (F-statistic):           1.38e-08
Time:                        15:56:55   Log-Likelihood:                -57.486
No. Observations:                  70   AIC:                             119.0
Df Residuals:                      68   BIC:                             123.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.4520      0.438     10.163      0.000       3.578       5.326
RLS           -0.3464      0.054     -6.449      0.000      -0.454      -0.239
==============================================================================
Omnibus:                        6.895   Durbin-Watson:                   2.152
Prob(Omnibus):                  0.032   Jarque-Bera (JB):                6.193
Skew:                           0.694   Prob(JB):                       0.0452
Kurtosis:                       3.446   Cond. No.                         54.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

===== P1 ~ Pengeluaran =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.259
Model:                            OLS   Adj. R-squared:                  0.249
Method:                 Least Squares   F-statistic:                     23.82
Date:                Fri, 28 Nov 2025   Prob (F-statistic):           6.69e-06
Time:                        15:56:55   Log-Likelihood:                -63.675
No. Observations:                  70   AIC:                             131.3
Df Residuals:                      68   BIC:                             135.8
Df Model:                           1
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           3.9270      0.470      8.352      0.000       2.989       4.865
Pengeluaran    -0.0002    4.1e-05     -4.881      0.000      -0.000      -0.000
==============================================================================
Omnibus:                        4.002   Durbin-Watson:                   2.461
Prob(Omnibus):                  0.135   Jarque-Bera (JB):                3.854
Skew:                           0.523   Prob(JB):                        0.146
Kurtosis:                       2.521   Cond. No.                     7.40e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.4e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

===== P1 ~ TPT =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.015
Method:                 Least Squares   F-statistic:                  0.001981
Date:                Fri, 28 Nov 2025   Prob (F-statistic):              0.965
Time:                        15:56:55   Log-Likelihood:                -74.187
No. Observations:                  70   AIC:                             152.4
Df Residuals:                      68   BIC:                             156.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.6703      0.250      6.670      0.000       1.171       2.170
TPT           -0.0019      0.042     -0.045      0.965      -0.086       0.082
==============================================================================
Omnibus:                        4.879   Durbin-Watson:                   1.861
Prob(Omnibus):                  0.087   Jarque-Bera (JB):                4.857
Skew:                           0.633   Prob(JB):                       0.0881
Kurtosis:                       2.749   Cond. No.                         18.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

===== P1 ~ Kepadatan =====
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.134
Model:                            OLS   Adj. R-squared:                  0.121
Method:                 Least Squares   F-statistic:                     10.50
Date:                Fri, 28 Nov 2025   Prob (F-statistic):            0.00185
Time:                        15:56:55   Log-Likelihood:                -69.162
No. Observations:                  70   AIC:                             142.3
Df Residuals:                      68   BIC:                             146.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.8833      0.105     17.985      0.000       1.674       2.092
Kepadatan     -0.0001   3.24e-05     -3.240      0.002      -0.000   -4.04e-05
==============================================================================
Omnibus:                        6.002   Durbin-Watson:                   2.184
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                6.135
Skew:                           0.706   Prob(JB):                       0.0465
Kurtosis:                       2.669   Cond. No.                     4.29e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.29e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

STEP 3 — Bangun model regresi linier berganda (X1…X6)

Lakukan:
- uji F
- uji t
- cek VIF
- backward elimination kalau ada variabel tidak signifikan
- pilih model final

In [11]:
X_cols = ["UHH","HLS","RLS","Pengeluaran","TPT","Kepadatan"]
X_train = sm.add_constant(df_train[X_cols])
y_train = df_train["P1"]

model_full = sm.OLS(y_train, X_train).fit()
print(model_full.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.436
Model:                            OLS   Adj. R-squared:                  0.383
Method:                 Least Squares   F-statistic:                     8.124
Date:                Fri, 28 Nov 2025   Prob (F-statistic):           1.62e-06
Time:                        15:57:33   Log-Likelihood:                -54.130
No. Observations:                  70   AIC:                             122.3
Df Residuals:                      63   BIC:                             138.0
Df Model:                           6
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          13.6849      4.852      2.820      0.006       3.988      23.382
UHH            -0.1476      0.072     -2.050      0.044      -0.291      -0.004
HLS             0.1669      0.224      0.745      0.459      -0.281       0.614
RLS            -0.3489      0.234     -1.492      0.141      -0.816       0.118
Pengeluaran -4.509e-06    6.9e-05     -0.065      0.948      -0.000       0.000
TPT            -0.0610      0.048     -1.258      0.213      -0.158       0.036
Kepadatan     4.17e-05    5.4e-05      0.772      0.443   -6.63e-05       0.000
==============================================================================
Omnibus:                        2.557   Durbin-Watson:                   2.114
Prob(Omnibus):                  0.278   Jarque-Bera (JB):                1.919
Skew:                           0.391   Prob(JB):                        0.383
Kurtosis:                       3.216   Cond. No.                     8.61e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.61e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [13]:
# cek uji multikolinearitas (VIF)
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

vif_df = pd.DataFrame()
vif_df["feature"] = X_cols
vif_df["VIF"] = [variance_inflation_factor(df_train[X_cols].values, i)
                 for i in range(len(X_cols))]

vif_df

       feature          VIF
0          UHH   620.245192
1          HLS  1877.487423
2          RLS   602.106523
3  Pengeluaran   143.829491
4          TPT    16.290746
5    Kepadatan     6.254313

In [14]:
# Backward elimination jika ada variabel tidak signifikan
def backward_elimination(X, y, alpha=0.05):
    X = sm.add_constant(X)
    while True:
        model = sm.OLS(y, X).fit()
        pvals = model.pvalues.drop("const")
        max_p = pvals.max()
        if max_p > alpha:
            drop_var = pvals.idxmax()
            print("Drop:", drop_var, "(p =", max_p, ")")
            X = X.drop(columns=[drop_var])
        else:
            break
    return model, X.columns

model_final, selected_features = backward_elimination(df_train[X_cols], y_train)
print(selected_features)
print(model_final.summary())

Drop: Pengeluaran (p = 0.9481303121317743 )
Drop: HLS (p = 0.45650069358910317 )
Drop: Kepadatan (p = 0.6487857729102886 )
Drop: TPT (p = 0.30751396758945326 )
Index(['const', 'UHH', 'RLS'], dtype='object')
                            OLS Regression Results
==============================================================================
Dep. Variable:                     P1   R-squared:                       0.420
Model:                            OLS   Adj. R-squared:                  0.403
Method:                 Least Squares   F-statistic:                     24.28
Date:                Fri, 28 Nov 2025   Prob (F-statistic):           1.17e-08
Time:                        15:58:59   Log-Likelihood:                -55.107
No. Observations:                  70   AIC:                             116.2
Df Residuals:                      67   BIC:                             123.0
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         12.0457      3.524      3.418      0.001       5.011      19.080
UHH           -0.1141      0.053     -2.171      0.034      -0.219      -0.009
RLS           -0.2262      0.076     -2.970      0.004      -0.378      -0.074
==============================================================================
Omnibus:                        4.135   Durbin-Watson:                   2.123
Prob(Omnibus):                  0.126   Jarque-Bera (JB):                3.255
Skew:                           0.452   Prob(JB):                        0.196
Kurtosis:                       3.548   Cond. No.                     4.10e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.1e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

STEP 4 — Prediksi tahun 2023 (test set)

- Ambil model final dari train (2021–2022)
- Prediksi P1 tahun 2023
- Hitung MAE, RMSE, MAPE

In [15]:
use_cols = [c for c in selected_features if c != "const"]

X_test = sm.add_constant(df_test[use_cols])
df_test["P1_pred"] = model_final.predict(X_test)

df_test[["Wilayah", "Tahun", "P1", "P1_pred"]]

                    Wilayah  Tahun    P1   P1_pred
70        Kabupaten Cilacap   2023  1.54  1.904130
71       Kabupaten Banyumas   2023  1.78  1.826345
72    Kabupaten Purbalingga   2023  2.52  2.015824
73   Kabupaten Banjarnegara   2023  2.34  1.998929
74        Kabupaten Kebumen   2023  2.89  1.845718
75      Kabupaten Purworejo   2023  1.78  1.552569
76       Kabupaten Wonosobo   2023  2.60  2.254508
77       Kabupaten Magelang   2023  1.73  1.812560
78       Kabupaten Boyolali   2023  1.02  1.519915
79         Kabupaten Klaten   2023  1.70  1.157159
80      Kabupaten Sukoharjo   2023  1.17  0.938099
81       Kabupaten Wonogiri   2023  1.32  1.577282
82    Kabupaten Karanganyar   2023  1.22  1.139566
83         Kabupaten Sragen   2023  2.15  1.599342
84       Kabupaten Grobogan   2023  1.48  1.838897
85          Kabupaten Blora   2023  1.35  1.921784
86        Kabupaten Rembang   2023  2.52  1.770161
87           Kabupaten Pati   2023  1.64  1.567267
88          Kabupaten Kudus   2023  0.99  1.165279
89         Kabupaten Jepara   2023  1.01  1.503132
90          Kabupaten Demak   2023  1.83  1.551062
91       Kabupaten Semarang   2023  0.82  1.556380
92     Kabupaten Temanggung   2023  0.99  1.705856
93         Kabupaten Kendal   2023  1.19  1.789572
94         Kabupaten Batang   2023  1.85  1.908076
95     Kabupaten Pekalongan   2023  1.30  1.929380
96       Kabupaten Pemalang   2023  2.40  2.139781
97          Kabupaten Tegal   2023  0.88  2.172103
98         Kabupaten Brebes   2023  2.98  2.617454
99            Kota Magelang   2023  0.74  0.703450
100          Kota Surakarta   2023  1.00  0.701924
101           Kota Salatiga   2023  0.75  0.613410
102           Kota Semarang   2023  0.54  0.714106
103         Kota Pekalongan   2023  0.82  1.434393
104              Kota Tegal   2023  0.86  1.426312

In [16]:
y_true = df_test["P1"]
y_pred = df_test["P1_pred"]

mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

print("MAE:", mae)
print("RMSE:", rmse)
print("MAPE:", mape)

MAE: 0.4085508622863201
RMSE: 0.4969237130580759
MAPE: 32.0769482637246